---

  # needed for docker, see: https://forums.aws.amazon.com/thread.jspa?messageID=574126
- name: enable repos for docker
  shell: 'yum-config-manager --enable rhui-REGION-rhel-server-extras'
  delegate_to: "{{item}}"
  remote_user: "{{amazon_user}}"
  become: true
  register: rs
  failed_when: "'Repository epel is listed more than once' in rs.stderr"
  with_items:
   - "{{master_public_ip}}"
   - "{{node1_public_ip}}"
   - "{{node2_public_ip}}"

- name: install pre-req packages on bastion
  yum:
    name: "{{item}}"
    state: "present"
  delegate_to: "{{bastion_public_ip}}"
  remote_user: "{{amazon_user}}"
  become: true
  with_items:
    - "git"
    - "@Development Tools"
#    - "python36u-pip"
    - "openssl-devel"
    - "python-devel"
    - "gcc"
    - "libffi-devel"

- name: install ansible on bastion
  pip:
    name: ansible
    version: 2.7.0
  delegate_to: "{{bastion_public_ip}}"
  remote_user: "{{amazon_user}}"
  become: true

- name: install docker on master and nodes
  yum:
    name: "docker"
    state: "present"
  delegate_to: "{{item}}"
  remote_user: "{{amazon_user}}"
  become: true
  with_items:
   - "{{master_public_ip}}"
   - "{{node1_public_ip}}"
   - "{{node2_public_ip}}"

- name: enable docker on master and nodes
  systemd:
     name: docker
     enabled: yes
     state: started
  delegate_to: "{{item}}"
  remote_user: "{{amazon_user}}"
  become: true
  with_items:
   - "{{master_public_ip}}"
   - "{{node1_public_ip}}"
   - "{{node2_public_ip}}"


