---

- name: copy inventory for openshift istallation
  template:
    src: "../files/openshift_inventory.cfg"
    dest: "~{{amazon_user}}/openshift_inventory.cfg"
  delegate_to: "{{bastion_public_ip}}"
  remote_user: "{{amazon_user}}"

- name: checkout openshift ansible repo on bastion
  git:
    repo: "https://github.com/openshift/openshift-ansible"
    dest: "~{{amazon_user}}/openshift-ansible"
    version: "{{openshift_branch}}"
  delegate_to: "{{bastion_public_ip}}"
  remote_user: "{{amazon_user}}"

- name: copy inventory for openshift istallation
  template:
    src: "../files/install-openshift.sh"
    dest: "~{{amazon_user}}/install-openshift.sh"
    mode: "0775"
  delegate_to: "{{bastion_public_ip}}"
  remote_user: "{{amazon_user}}"

- name: set up yum repo for various deps
  template:
    src: "../files/openshift-310.repo"
    dest: "/etc/yum.repos.d/openshift-310.repo"
    mode: "0775"
  delegate_to: "{{bastion_public_ip}}"
  remote_user: "{{amazon_user}}"

- name: provide details to check installation
  debug:
   msg: "Check file install-openshift.log in Bastion 'ssh ec2-user@{{bastion_public_ip}}' "

- name: run openshift installation script
  shell: './install-openshift.sh |& tee install-openshift.log'
  delegate_to: "{{bastion_public_ip}}"
  remote_user: "{{amazon_user}}"
