---

- name: create DNS zone for openshift
  route53_zone:
     zone: "{{dns_zone}}"
     state: "{{state}}"
     vpc_id: "{{vpc_id}}"
     vpc_region: "{{region}}"
     comment: "Internal zone for Openshift"
  register: aws_zone 

- name: add bastion dns
  route53:
    hosted_zone_id: "{{aws_zone['zone_id']}}"
    zone: "{{dns_zone}}"
    record: "bastion.{{dns_zone}}"
    type: A
    ttl: 300
    value: "{{bastion_private_ip}}"
    wait: yes
    vpc_id: "{{vpc_id}}"
    private_zone: true
    state: "create"
    overwrite: yes

- name: add master dns 
  route53:
    hosted_zone_id: "{{aws_zone['zone_id']}}"
    zone: "{{dns_zone}}"
    record: "master.{{dns_zone}}"
    type: A
    ttl: 300
    value: "{{master_private_ip}}"
    wait: yes
    vpc_id: "{{vpc_id}}"
    private_zone: true
    state: "create"
    overwrite: yes

- name: add node1 dns 
  route53:
    hosted_zone_id: "{{aws_zone['zone_id']}}"
    zone: "{{dns_zone}}"
    record: "node1.{{dns_zone}}"
    type: A
    ttl: 300
    value: "{{node1_private_ip}}"
    wait: yes
    vpc_id: "{{vpc_id}}"
    private_zone: true
    state: "create"
    overwrite: yes

- name: add node2 dns 
  route53:
    hosted_zone_id: "{{aws_zone['zone_id']}}"
    zone: "{{dns_zone}}"
    record: "node2.{{dns_zone}}"
    type: A
    ttl: 300
    value: "{{node2_private_ip}}"
    wait: yes
    vpc_id: "{{vpc_id}}"
    private_zone: true
    state: "create"
    overwrite: yes

- name: add public dns
  route53:
    zone: "{{public_dns_zone}}"
    record: "{{public_dns_zone}}"
    type: A
    ttl: 300
    value: "{{master_public_ip}}"
    wait: yes
    state: "create"
    overwrite: yes

- name: add public wildcard dns
  route53:
    zone: "{{public_dns_zone}}"
    record: "*.{{public_dns_zone}}"
    type: A
    ttl: 300
    value: "{{master_public_ip}}"
    wait: yes
    state: "create"
    overwrite: yes